import type { Metadata } from "next";

import "./globals.css";

import Footer from "./_components/footer/footer";
import Navbar from "./_components/navbar/navbar";

export const metadata: Metadata = {
  title: "MMM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" bg-smoke-mmm"
      >
        <Navbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}

