import type { Metadata } from "next";

// import "./globals.css";

// import Footer from "@/app/_components/footer/footer";


export const metadata: Metadata = {
  title: "MMM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-smoke-mmm">{children}</body>
    </html>
  );
}
